/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_oneapm_jni_ThreadJni */

#ifndef _Included_com_oneapm_jni_ThreadJni
#define _Included_com_oneapm_jni_ThreadJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_oneapm_jni_ThreadJni
 * Method:    CreateThread
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_oneapm_jni_ThreadJni_CreateThread
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
